### ISSUE TITLE
Title with line breaks showing LF character

### ISSUE THREAD

**Issue by sarah-sr** [KyoriPowered/adventure-platform#133]
The title I need to display is too large to fit on screen so need to add line breaks. But instead of moving onto the next line, LF character is displayed instead.

**Comment by KingOfSquares** [comment]
Some parts in Minecraft do not support line breaks (e.g lore text), I'm guessing this is the case here as well since the idea is Title and subtitle each has their own line to prevent the whole screen potentially filling up.

Tested in vanilla 1.19.4:
<img width="1020" alt="Screenshot 2023-05-24 at 19 26 42" src="https://github.com/KyoriPowered/adventure-platform/assets/19822231/dbeb3023-5ca2-419a-91d6-1fd4d8f8cbb3">

**Comment by sarah-sr** [comment]
Seems like you're right. It doesn't look connected to Kyori. I made an effort to test both Bedrock and Java and this issue is consistent in Java only.

Bedrock 1.19.83
![bukkitBedrockTitleLinebreak](https://github.com/KyoriPowered/adventure-platform/assets/9202520/8bffde09-593b-47e2-b9d1-b01e794fb695)

Java 1.19.4
![bukkitJavaTitleLinebreak](https://github.com/KyoriPowered/adventure-platform/assets/9202520/4f8f1775-518c-4404-a473-fd9b8eceae9b)
