### ISSUE TITLE
BungeeCord Audience sendMessage: source not working with client

### ISSUE THREAD

**Issue by petomka** [KyoriPowered/adventure-platform#47]
The following has been tested on bungeecord, not on spigot however. This is not the exact code, but it shows the logic I've been using and what I already debugged.
```java
public void sendChatMessage(CommandSender sender, UUID sourceId, Component component) {
    Identity identity = Identity.identity(sourceId);
    Audience audience = /*... get BungeeAudiences ...*/.sender(sender);
    audience.sendMessage(source, component, MessageType.CHAT);
}
```
I debugged using two of my own accounts. On one account, I added the other account to my local ignore list using the social options screen (default keybind is `P`).
When I was sending a message using the code above with the blocked account as identity, I expected to not see that message with my other account - yet it still came through.

**Comment by marcbal** [comment]
Probably because the following code is just ignoring the `source` argument:
https://github.com/KyoriPowered/adventure-platform/blob/851884b016f4efb46f35c3dabf389c3b35491415/platform-bungeecord/src/main/java/net/kyori/adventure/platform/bungeecord/BungeeFacet.java#L104-L111

Bungeecord ProxiedPlayer interface now provides a `sendMessage` method with UUID parameter:
https://github.com/SpigotMC/BungeeCord/blob/bda160562792a913cba3a65ba4996de60d0d6d68/api/src/main/java/net/md_5/bungee/api/connection/ProxiedPlayer.java#L82-L96

**Comment by zml2008** [comment]
ProxiedPlayer provides a `sendMessage` with a `UUID` parameter and one with a `ChatMessageType` parameter, but not one with both for some reason :(

**Comment by marcbal** [comment]
Sadly, yes. Looking at the implementation, using the one with UUID parameter imply `ChatMessageType.CHAT`, so it should be an easy fix with some if-else statement.
Another solution would be to make the `sendMessage(ChatMessageType, UUID, BaseComponent)` part of the API in bungeecord (it’s only in the implementation class)
