### ISSUE TITLE
Sounds played with Emitter.self() on platform-bukkit don't play.

### ISSUE THREAD

**Issue by Symphonic3** [KyoriPowered/adventure-platform#55]
They play fine on paper-api. No errors in console or on the client.

**Comment by kezz** [comment]
Could be due to this section of code. Unless I'm missing something amongst the platform fun this should be falling back to playing the sound normally rather than doing nothing.

https://github.com/KyoriPowered/adventure-platform/blob/851884b016f4efb46f35c3dabf389c3b35491415/platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java#L478-L480

**Comment by zml2008** [comment]
should be fixed, please confirm

**Comment by kezz** [comment]
I'm going to close this as I'm pretty sure the fix does work now. If it doesn't, please comment and we can re-open this issue.
